include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    unused_local_variable: warning
    dead_code: error
    
# Custom lint rules can be added here
linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - annotate_overrides

  